### ISSUE TITLE
Update from source

### ISSUE THREAD

**Issue by brendon** [markmcconachie/normalize-rails#17]
Hi there, would you mind bringing in the latest normalise.css from https://github.com/necolas/normalize.css (I assume?) and releasing a new gem?

The latest version removes some annoying table resets per:
https://github.com/necolas/normalize.css/issues/506

**Comment by brendon** [comment]
I should add, it's the version in `master` that has the important changes. The actual download link on his page still links to an old version.

**Comment by markmcconachie** [comment]
Hey brendon, unfortunatly, I don't have time to look at this right now so I have added you to this repo so you can care for it :P  

I don't think we should push a production versioned gem with pre-release code though

**Comment by brendon** [comment]
Hi Mark, thanks for that lol! This happened to me with acts_as_list. At least this one is a bit simpler. I've asked them if they'd release a new tagged version.
