### ISSUE TITLE
Permission to deploy a new gem version

### ISSUE THREAD

**Issue by brendon** [markmcconachie/normalize-rails#23]
Hi @markmcconachie, are you able to add me to the list of gem maintainers:

```
gem owner normalize-rails --add brendon@spike.net.nz
```

I'm wanting to release the latest `5.0.0` version of `normalize.css` :)

**Comment by tysongach** [comment]
Would love to see this get published!

How can we do better at tracking Normalize and getting releases of normalize-rails published to RubyGems quicker? Can this be more automated?

**Comment by brendon** [comment]
I'm not sure there is a way to make it automated per-se. That could also be dangerous :)

But someone being able to be notified when a new version is released (new tag?) would be a handy way to go :) @markmcconachie, can you action this issue?

**Comment by brendon** [comment]
I'm trying this service out: https://allmychanges.com should work well :)

**Comment by tysongach** [comment]
Not _completely_ automated, just _more_ automated 😉.

I help maintain [Bourbon](https://github.com/thoughtbot/bourbon) and I’ve started piping RSS feeds of GitHub releases (e.g. `https://github.com/thoughtbot/bourbon/releases.atom`) for services/dependencies into Slack, which helps me keep track of things.

👍

**Comment by brendon** [comment]
Hey that's smart :) I don't use Slack, but if I did, that would work well :)

**Comment by tysongach** [comment]
@markmcconachie Any update here?

**Comment by meric426** [comment]
@paulbeattie any update here?

**Comment by mbillard** [comment]
Any chance of getting new gem releases soon?

**Comment by brendon** [comment]
I've flicked an email to Mark to see if he can add me as a gem maintainer.

**Comment by brendon** [comment]
@markmcconachie, are you keen to hand this over?

**Comment by paulbeattie** [comment]
@brendon sorry about the delay. Added you as a Gem owner.

**Comment by brendon** [comment]
I fought through my want to procrastinate on this one and have released `8.0.1`. Enjoy! :D 🥳

**Comment by brendon** [comment]
Also, thank you @paulbeattie  :D
